services:
  tomcat:
    image:  tomcat:9.0.98-jdk8-temurin-noble
    ports:
      - "8888:8080"
    volumes:
      - ./hti-ss-web/target/ss-tool.war:/usr/local/tomcat/webapps/ss-tool.war
      - ./dockerConfigs/context.xml:/usr/local/tomcat/conf/context.xml
    depends_on:
      - mysql
    environment:
      - JAVA_OPTS=-Xmx4096m -Xms4096m
    links:
      - mysql:container-mysql
    command: bash -c "rm -rf /usr/local/tomcat/webapps.dist && catalina.sh run"

  mysql:
    image: mysql:8.1
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - ./dockerConfigs/mysql:/docker-entrypoint-initdb.d/:rw
      # - ./dockerConfigs/dbSetup.sql:/data/application/dbSetup.sql    
      # command: --init-file /data/application/dbSetup.sql
